In [2]:
import pandas as pd
import numpy as np

df_imdb_fr = pd.read_csv("export/df_imdb_fr.csv", on_bad_lines='skip')

df_imdb_fr.head()

<ipython-input-2-8f3e38721f11>:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_imdb_fr = pd.read_csv("export/df_imdb_fr.csv", on_bad_lines='skip')

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000002,2,Le clown et ses chiens,FR,\N,imdbDisplay,\N,0
1,tt0000003,8,Pauvre Pierrot,FR,\N,imdbDisplay,\N,0
2,tt0000004,2,Un bon bock,FR,\N,imdbDisplay,\N,0
3,tt0000010,17,La sortie de l'usine Lumière,FR,\N,alternative,\N,0
4,tt0000012,18,L'arrivée d'un train à La Ciotat,FR,\N,imdbDisplay,\N,0

In [3]:
df_tournage_films = pd.read_csv("export/df_tournage_films.csv", on_bad_lines='skip')

df_tournage_films.head()

,titre,réalisateur,producteur,postal,debut,fin,latitude,longitude,rive
0,TOUT S'EST BIEN PASSE,Francois OZON,MANDARIN PRODUCTION,75013,2020-08-20,2020-08-21,48.835660,2.348315,gauche
1,Une jeune fille qui va bien,Sandrine Kiberlain,CURIOSA FILMS,75004,2020-08-31,2020-09-01,48.854533,2.361694,droite
2,French Exit,Azazel Jacobs,Same Player,75012,2019-12-04,2019-12-04,48.850067,2.376519,droite
3,FIN DE MATINEE,Hiroshi NISHATANI,COMME DES CINEMAS,75004,2018-11-05,2018-11-05,48.854112,2.354679,droite
4,HORS NORMES,Eric Toledano et Olivier Nakache,ADNP QUAD FILMS,75001,2018-11-05,2018-11-06,48.865744,2.327446,droite